SELECT * FROM PCAJG.dit_datos_info_tributaria WHERE nif = 'Z2984149L'  ID_DATOS_INFO_TRIBUTARIA= 11992773   nif = '60339247N'
SELECT * FROM PCAJG.DPA_DATOS_PERSONALES_AEAT WHERE ID_DATOS_INFO_TRIBUTARIA= 12256379
SELECT MAX(FECHAESTADOCIVIL) FROM PCAJG.DPA_DATOS_PERSONALES_AEAT


20451742209211366

SELECT max(ID_DATOS_INFO_TRIBUTARIA) FROM PCAJG.DHA_DATOS_HIJOS_AEAT  WHERE ID_DATOS_INFO_TRIBUTARIA= 7480793
SELECT * FROM PCAJG.con_conceptos_aeat
SELECT * FROM PCAJG.DIAE_DATOS_IAE WHERE ejercicio = 2023
SELECT * FROM pcajg.INF_INGRESOS_FAMILIARES WHERE id_solicitante = 12256379
SELECT * FROM PCAJG.DCA_DATOS_CONYUGE_AEAT  WHERE ID_DATOS_INFO_TRIBUTARIA = 12256379

2055174221564092173453469W
73453469W

SELECT * FROM PCAJG.SOL_SOLICITUDES WHERE ID_SOLICITUD_EXT  LIKE '%73453469W' ID_SOLICITANTE = 10066916
SELECT * FROM PCAJG.SOL_SOLICITUDES WHERE TO_CHAR(FECHA_FIRMA,'MMYYYY') = (SELECT TO_CHAR(SYSDATE,'MMYYYY') FROM DUAL) AND id_colegio = 2045 AND ID_TIPO_ESTADO_SOLICITUD NOT IN (1,15)
ORDER BY FECHA_FIRMA DESC


SELECT * FROM PCAJG.PDF_DETALLE_SOLICITUD  
SELECT * FROM pcajg.IIT_IMPORTE_INFO_TRIBUTARIA WHERE IMPORTE = 19670.46 AND IMPORTE < 19671 

SELECT * FROM pcajg.OIA_OTROS_IMPORTES_AEAT 
SELECT * FROM pcajg.OIA_OTROS_IMPORTES_AEAT WHERE ID_DATOS_INFO_TRIBUTARIA= 5528850 DESCRIPCION = 'NIVEL DE RENTA' AND  5528850
SELECT max(ID_DATOS_INFO_TRIBUTARIA) FROM pcajg.OIA_OTROS_IMPORTES_AEAT WHERE ID_DATOS_INFO_TRIBUTARIA= 6516314

SELECT * FROM pcajg.PFI_PERSONA_FISICA WHERE PCAJG.PFI_PERSONA_FISICA.NUM_DOC_IDENTIDAD = 'Z2984149L' AND id_solicitante

19,670.46

SELECT 
       TO_CHAR(SYSDATE, 'YYYY-MM') as "fecha",
       SOL_SOLICITUDES.ID_COLEGIO as "idcolegio",
       SUBSTR(TOS_TIPO_ORIGEN_SOLICITUD.DESC_TIPO_ORIGEN_DATOS,32,20) as "origen",
       SIC_SISTEMAS_CLIENTE.DESC_SISTEMA_CLIENTE as "sistema",  
       COUNT(*) as  "solicitudes",
       COUNT(DISTINCT(SUBSTR(ID_SOLICITUD_EXT,18,9))) AS "solicitantes" 
FROM PCAJG.SOL_SOLICITUDES
     INNER JOIN PCAJG.TOS_TIPO_ORIGEN_SOLICITUD ON SOL_SOLICITUDES.ID_TIPO_ORIGEN_SOLICITUD=TOS_TIPO_ORIGEN_SOLICITUD.ID_TIPO_ORIGEN_SOLICITUD
     LEFT JOIN PCAJG.RSS_SOLICITUD_SISTEMA_CLIENTE ON SOL_SOLICITUDES.ID_SOLICITUD=RSS_SOLICITUD_SISTEMA_CLIENTE.ID_SOLICITUD
     LEFT JOIN PCAJG.SIC_SISTEMAS_CLIENTE ON RSS_SOLICITUD_SISTEMA_CLIENTE.ID_SISTEMA_CLIENTE=SIC_SISTEMAS_CLIENTE.ID_SISTEMA_CLIENTE
WHERE
     TO_CHAR(FECHA_FIRMA,'MMYYYY') = (SELECT TO_CHAR(SYSDATE,'MMYYYY') FROM DUAL)
     AND ID_TIPO_ESTADO_SOLICITUD NOT IN (1,15)
GROUP BY SOL_SOLICITUDES.ID_COLEGIO,TOS_TIPO_ORIGEN_SOLICITUD.DESC_TIPO_ORIGEN_DATOS,SIC_SISTEMAS_CLIENTE.DESC_SISTEMA_CLIENTE




SELECT * FROM PCAJG.DIC_DATOS_INFO_CATASTRAL ddic 


